force-app/main/default/objects/BatchTestObject__c/BatchTestObject__c.object-meta.xml
<CustomObject>
    <description>simple object to test</description>
    <label>BatchTestObject</label>
    <nameField>
        <label>BatchTestObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BatchTestObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchTestObject__c/fields/IDNumber__c.field-meta.xml
<CustomField>
    <fullName>IDNumber__c</fullName>
    <label>IDNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BatchTestObject__c/fields/LastUpdate__c.field-meta.xml
<CustomField>
    <fullName>LastUpdate__c</fullName>
    <label>LastUpdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestScheduledBatchTestObject.cls
@isTest
public with sharing class TestScheduledBatchTestObject {

    // Dummy CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '20 30 8 10 2 ?';

    @isTest
    public static void TestIt() {

        List<BatchTestObject__c> blist = new List<BatchTestObject__c>();

        for (Integer x = 0; x < 500; x++) {
            BatchTestObject__c b = new BatchTestObject__c(Name = 'test ' + x, IDNumber__c = x);
            blist.add(b);
        }

        insert blist;

        test.StartTest();
        String jobId = System.schedule('ScheduledApexTest',
                CRON_EXP,
                new ScheduledBatchTestObject());

        Test.stopTest();

        //verify 


        for(List<BatchTestObject__c> l : [Select LastUpdate__c from BatchTestObject__c]) {
            for (BatchTestObject__c b: l) {
                system.assertEquals(system.today(), b.LastUpdate__c);
            }
        } 

    }

}