force-app/main/default/objects/BatchTestObject__c/BatchTestObject__c.object-meta.xml
<CustomObject>
    <description>simple object to test</description>
    <label>BatchTestObject</label>
    <nameField>
        <label>BatchTestObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BatchTestObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchTestObject__c/fields/LastUpdate__c.field-meta.xml
<CustomField>
    <fullName>LastUpdate__c</fullName>
    <label>LastUpdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ScheduledBatchTestObject.cls
public with sharing class ScheduledBatchTestObject implements Schedulable {
    
    
    public ScheduledBatchTestObject() {
    }

    public void execute(SchedulableContext ctx) {
        List<BatchTestObject__c> updates = new List<BatchTestObject__c>();
        for(List<BatchTestObject__c> b: [Select LastUpdate__c FROM BatchTestObject__c] ) {
            for(BatchTestObject__c bb: b) {
                bb.LastUpdate__c = system.today();
                updates.add(bb);
            }
        }

        update updates;
    }

}